### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by krakkajack** [Jaycar-Electronics/Digital-Photo-Frame#3]
Hi,
Tried to compile this project and got the following error report:

Arduino: 1.8.12 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/WiFiClientSecureBearSSL.h:30:0,

                 from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/WiFiClientSecure.h:41,

                 from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/WiFiServerSecure.h:20,

                 from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/ESP8266WiFi.h:41,

                 from C:\Users\sccph\OneDrive - Scenechange\Documents\Arduino\Digital-Photo-Frame-master\espCode\espcode.ino:7:

**C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:40:23: error: 'FS' has not been declared

     int initCertStore(FS &fs, const char *indexFileName, const char *dataFileName);**

                       ^

C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WiFi\src/CertStoreBearSSL.h:46:5: error: 'FS' does not name a type

     FS *_fs = nullptr;

     ^

In file included from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer-impl.h:30:0,

                 from C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/ESP8266WebServer.h:235,

                 from C:\Users\sccph\OneDrive - Scenechange\Documents\Arduino\Digital-Photo-Frame-master\espCode\espcode.ino:9:

C:\Users\sccph\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3\libraries\ESP8266WebServer\src/detail/RequestHandlersImpl.h:67:29: error: expected ')' before '&' token

     StaticRequestHandler(FS &fs, const char* path, const char* uri, const char* cache_header)

                             ^

espcode:287:1: error: expected '}' at end of input

 }

 ^

espcode:287:1: error: expected unqualified-id at end of input

espcode:287:1: error: expected '}' at end of input

exit status 1
expected '}' at end of input

I'm pretty sure the last three errors just flow on from the first three.
tim

**Comment by Jaycar-Electronics** [comment]
hmm 🤔 

to me it seems like something wrong with the ESP libraries; as it's something relating to FS not being defined in their functions... 

I'll investigate this a little more and try and get a solution, please wait

**Comment by Jaycar-Electronics** [comment]
Issue relates to having the latest version of ESP8266 boards installed. 

If you go to " Tools > Boards > Boards manager " and downgrade ESP8266 to "2.5.2"  ( and set exceptions to disabled ) then it will compile fine. 

![image](https://user-images.githubusercontent.com/43460991/77594564-f5c7da80-6f4a-11ea-8c19-c98e584b5d6d.png)

Related issues:
- https://github.com/luc-github/ESP3D/issues/352

it seems like the esp8266 guys have a "update and forget" problem as some other code bases rely on changes in the 2.4.2 versions of ESP, breaking in 2.5.2
- https://github.com/esp8266/Arduino/issues/5784

For the time being I'll have to amend the project page and mention it specifically. We might have to work on a 2.6.3 branch in the future.

Can you confirm that it works?

**Comment by krakkajack** [comment]
Wow, thanks for the fast response. Have to wait til I get home from work and I'll get on it.

**Comment by krakkajack** [comment]
Hi,
Yes, I downgraded to 2.5.2, and it compiled and loaded, but I had to then upgrade again for the Data Upload tool to work. A bit of shuffling around but it's all working well now.
Thanks for your help!
tim
